# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-tcg-back-office:
    build:
      target: development
    image: ffc-tcg-back-office-development
    container_name: ffc-tcg-back-office-development
    ports:
      - "3050:3050"
      - "9250:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
