services:
  ffc-tcg-back-office:
    build:
      context: .
      target: production
    image: ffc-tcg-back-office
    container_name: ffc-tcg-back-office
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-tcg-back-office-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
