environment: production
environmentCode:
name: ffc-tcg-back-office
namespace: ffc-tcg
workstream: ffc-tcg
image: ffc-tcg-back-office

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-tcg-back-office-config-map

containerSecret:
  name: ffc-tcg-back-office-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3050

livenessProbe:
  path: /healthz
  port: 3050
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3050
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
